### ISSUE TITLE
Duda acerca de la validación de llaves en los tests

### ISSUE THREAD

**Issue by sbcontreras** [IIC3103-2024-01/help#10]
Después de someter mi backend a las pruebas, he encontrado una discrepancia en la validación de las claves en dos puntos de acceso particulares:  `/users` y  `/posts`. Aunque ambos puntos de acceso devuelven las claves requeridas, en el caso de /posts, la validación de las claves exige una correspondencia exacta con lo solicitado, mientras que en el caso de /users, se permite un número mayor de claves de las mínimas requeridas. Para clarificar este punto, proporcionaré más detalles:

**Endpoint `/users`:**
Actualmente, el endpoint `/users` devuelve una lista de objetos con un esquema que incluye las siguientes llaves: `id`, `username`, `avatar`, `created`, `updated` y `_count` . Sin embargo, la prueba automatizada no considera como un error la presencia de las llaves adicionales `updated` y `_count`. A mi parecer, este debería ser el comportamiento ideal ya que me permite tener un poco más de  información adicional para la implementación del frontend.

**Endpoint `/posts`:**
El endpoint `/posts` por su parte, devuelve una lista de objetos con un esquema que incluye las llaves: `id`, `title`, `content`, `image`, `userId`, `created`, `updated` y `_count`. Aunque cuenta son los valores esperados, el resultado del test marca como error la presencia de las llaves adicionales `updated` y `_count`.

**Error Reportado:**
El error específico reportado por el test es el siguiente:

```
Traceback (most recent call last):
  File "/workspace/main.py", line 53, in run_tests
    test()
  File "/workspace/tests.py", line 245, in get_posts
    raise Exception(f"Post keys are not the expected ones: {post.keys()}")
Exception: Post keys are not the expected ones: dict_keys(['id', 'title', 'content', 'image', 'userId', 'created', 'updated', '_count'])
```

**Solicitud de Aclaración:**
La pregunta que me surge es si debo modificar la implementación de los endpoints para que coincida estrictamente con las llaves solicitadas en los tests, o si esto fue un detalle omitido en la configuración del test, considerando que  `/users` evalúa que el objeto contenga las llaves requeridas, pero no necesariamente que contenga únicamente esas.

**Comment by dedarritchon** [comment]
Hola @sbcontreras ,

Debes modificar la respuesta del endpoint /posts para que coicida exactamente con lo pedido en el enunciado. En el caso del endpoint /users simplemente se omitió la validación (fue un error al crear el test).

Saludos
