### ISSUE TITLE
Problema reset test

### ISSUE THREAD

**Issue by VicenteSaldana** [IIC3103-2024-01/help#18]
Tengo un problema con el tester, en que a veces me da como resultado todo OK, y otras veces me da error en la parte de reset. La verdad no entiendo de qué depende que algunas veces salga todo bien y otras salga error. Este es el error que me sale:

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/layers/google.python.runtime/python/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/layers/google.python.runtime/python/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/layers/google.python.runtime/python/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/layers/google.python.runtime/python/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/layers/google.python.runtime/python/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/layers/google.python.runtime/python/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='tarea-1-vicentesaldana.onrender.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/main.py", line 53, in run_tests
    test()
  File "/workspace/tests.py", line 160, in reset
    response = self._post(self.RESET_ENDPOINT, {})
  File "/workspace/tests.py", line 403, in _post
    response = requests.post(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tarea-1-vicentesaldana.onrender.com', port=443): Read timed out. (read timeout=15)

No sé si me puedan ayudar :(

Copié ese error hace 10 minutos, y ahora sin hacer ningún cambio volví a ver y me sale todo bien:
![Test_correctos](https://github.com/IIC3103-2024-01/help/assets/80849566/faec4daf-0a71-4cf6-8ba9-b20b336df316)
Por lo que realmente me da incertidumbre si dará error o no al momento de la corrección.

**Comment by arturokunder** [comment]
Vicente,
El `reset` está dando timeout, como se puede ver en la última línea de la traza:

```
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tarea-1-vicentesaldana.onrender.com', port=443): Read timed out. (read timeout=15)
```

Tu servicio está tomando más de 15 segundos en responder, y por eso el script falla.
Te sugiero, para evitar problemas, buscar alguna forma de optimizar este servicio. Por nuestro lado, veré si es factible aumentar el timeout de este servicio específico.

**Comment by dedarritchon** [comment]
@VicenteSaldana ,

Se subió el timeout del test a 90 segundos,

Saludos
