### ISSUE TITLE
No me funciona el deploy

### ISSUE THREAD

**Issue by saravialu** [IIC3103-2024-01/help#26]
Hola! Probé el deploy localmente y me funciona perfecto, pero cuando lo subo a render no me funciona, llega solo al bulid, después no me conecta con la base de datos. Revisé los parámetros y están bien pero no se por que no me conecta. Busque varias opciones en internet pero ninguna me funcionó

este es el error:
code: 'ECONNREFUSED',
      at afterConnectMultiple (node:net:1683:7) {
      at internalConnectMultiple (node:net:1116:18)
  parent: AggregateError [ECONNREFUSED]: 
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at Socket.emit (node:events:518:28)
    at Socket.reportStreamError (/opt/render/project/src/socialgram_backend/node_modules/pg/lib/connection.js:58:12)
    at Connection.emit (node:events:518:28)
    at Client._handleErrorEvent (/opt/render/project/src/socialgram_backend/node_modules/pg/lib/client.js:337:19)
    at Client._handleErrorWhileConnecting (/opt/render/project/src/socialgram_backend/node_modules/pg/lib/client.js:327:19)
    at Client._connectionCallback (/opt/render/project/src/socialgram_backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)
Unable to conect to db: ConnectionRefusedError [SequelizeConnectionRefusedError]

**Comment by arturokunder** [comment]
Respondido por interno.
